name: Deploy to Cloudflare pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: beta
          # flutter-version: 3.6.0-216.1

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Transpile
        run: |
          flutter build web --no-tree-shake-icons --web-renderer html

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy build/web --project-name=mastersync-web
